### ISSUE TITLE
Can not unzip pre-trained model and environment .

### ISSUE THREAD

**Issue by moonsh** [dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R#1]
Thank you for sharing your amazing work.

I would like to reimplement your work but I can't unzip your files ( pre-trained model.zip and evironment.zip). These files seem to be cracked.

Could you check these files?

Thank you,

**Comment by dtransposed** [comment]
Thank you @moonsh, I am on it.

**Comment by dtransposed** [comment]
> Thank you for sharing your amazing work.
> 
> I would like to reimplement your work but I can't unzip your files ( pre-trained model.zip and evironment.zip). These files seem to be cracked.
> 
> Could you check these files?
> 
> Thank you,

**Comment by dtransposed** [comment]
I have tested both .zip files now - cloned the whole repo on Ubuntu 18.04 and Windows 10 and checked the state of those files. They are intact. Please try again on your machine and make sure you are extracting the contents correctly. If the problem persists, we will try to find the solution.

**Comment by moonsh** [comment]
@dtransposed It's strange those files are just 1kb and I can't open these files. I am using windows 10.

**Comment by moonsh** [comment]
@dtransposed  I figured it out. When I downloaded the file one by one, the problem was solved. Thank you.

**Comment by dtransposed** [comment]
Hmm, still very unclear why you had problems...maybe some issues with LFS. Anyways, glad to see you have resolved the problem. Enjoy playing with the GEAR @moonsh !

**Comment by moonsh** [comment]
@dtransposed Yeah. I think so. Thank you so much.
