### ISSUE TITLE
how to get gear use the GPU?

### ISSUE THREAD

**Issue by vxgu86** [dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R#3]
how to get gear use the GPU?
and how to know that I am using GPU?

thanks

**Comment by dtransposed** [comment]
You need to install tensorflow-gpu and not just tensorflow in your ml-agents environment.

**Comment by vxgu86** [comment]
> You need to install tensorflow-gpu and not just tensorflow in your ml-agents environment.

thanks I will try
