### ISSUE TITLE
how can I visualize the train or inference , like the camera viewing in your article?

### ISSUE THREAD

**Issue by vxgu86** [dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R#4]
how can I visualize the train or inference , like the camera viewing in your article?
the PPO with segnet is soooo slow that Unity didn't correspond at all. Is there any thing that I missed? How can I see through the inference procedure?

**Comment by dtransposed** [comment]
1. You should have several cameras setup by default. By changing their position, you can manipulate the field of view. 
2. PPO with SegNet will be slow. Especially if your GPU is not top-notch. This is because you do bulky inference in real-time.
