### ISSUE TITLE
wondering for long time without figuring out the structure of the changed ml-agent you made

### ISSUE THREAD

**Issue by vxgu86** [dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R#5]
wondering for long time without figuring out the structure of the changed ml-agent you made, 
sorry for my dummy, but could you explain this for some shining?
and I did not figure out which version of ml-agents are you changing  based on?

**Comment by dtransposed** [comment]
I think I have addressed this in our private message exchange. If you have received an answer to your question, I would like to close the issue.
