### ISSUE TITLE
This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

### ISSUE THREAD

**Issue by rbarber68** [dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R#6]
I'm unable to clone this repo.  I'm getting this error when I try to clone it.

_batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R.git/info/lfs'_

Is there some other way to clone this?  Without unity-environment.zip there is no way to understand the unity3d side.

Thanks,
Russ

**Comment by dtransposed** [comment]
Try to clone this repo now. It should work. If not, the heavy .zip files can be directly downloaded here: https://drive.google.com/drive/folders/1lyWGaB2sBu2kq7q_wVTVVYs4Bgv11J-_?usp=sharing

**Comment by warmonger5** [comment]
Thak you for the link.
That really helped a lot
