### ISSUE TITLE
I have been trying to clonethis repo from many days but there has been an issue.

### ISSUE THREAD

**Issue by Ananya2720** [dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R#7]

**Comment by Ananya2720** [comment]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R.git/info/lfs'
please help me with this and provide me with a way with which i can clone this.
Thankyou,
ananya

**Comment by dtransposed** [comment]
Hey!

Sorry for the trouble. I will take care of it this week!

Cheers,
Damian

sob., 15 lut 2020 o 14:53 Ananya2720 <notifications@github.com> napisał(a):

**Comment by Ananya2720** [comment]
Hi!
The issue is not yet resolved.Can you please tell me the procedure to download the files,it will be really helpful.
Thanks,
Ananya

**Comment by dtransposed** [comment]
Try to clone this repo now. It should work. If not, the heavy .zip files can be directly downloaded here: https://drive.google.com/drive/folders/1lyWGaB2sBu2kq7q_wVTVVYs4Bgv11J-_?usp=sharing
