### ISSUE TITLE
Unable to clone repository due to limited LFS Bandwidth

### ISSUE THREAD

**Issue by warmonger5** [dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R#8]
I'm unable to clone this repo. I'm getting this error when I try to clone it.

batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/dtransposed/Reinforcement-Learning-With-Unity-G.E.A.R.git/info/lfs'

Is there some alternate method to clone it. If so, please reply.

Regards,
Akshay

**Comment by warmonger5** [comment]
Still the same problem is occurring while trying to clone the .zip files.

If possible could you send it privately?

**Comment by dtransposed** [comment]
I'm gonna post the fix today.

**Comment by dtransposed** [comment]
Try to clone this repo now. It should work. If not, the heavy .zip files can be directly downloaded here: https://drive.google.com/drive/folders/1lyWGaB2sBu2kq7q_wVTVVYs4Bgv11J-_?usp=sharing

Please give me feedback if this is a sufficient solution.
